---
- name: OpenShift Node Firewall Onboarding Workflow
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    node_name: "{{ target_node_name }}"

  tasks:
    - name: Remove Taint and Label from OpenShift Machine
      kubernetes.core.k8s:
        # Uses the OpenShift ServiceAccount Credential configured in AAP Step 2
        definition:
          apiVersion: v1
          kind: Machine
          metadata:
            name: "{{ node_name }}"
            labels:
              trigger-aap-onboarding: null # Setting null removes the label
          spec:
            taints: [] # Strips all onboarding taints from the Node
        validate_certs: false

    - name: Remove Taint and Label from OpenShift Node
      kubernetes.core.k8s:
        # Uses the OpenShift ServiceAccount Credential configured in AAP Step 2
        definition:
          apiVersion: v1
          kind: Node
          metadata:
            name: "{{ node_name }}"
            labels:
              trigger-aap-onboarding: null # Setting null removes the label
          spec:
            taints: [] # Strips all onboarding taints from the Node
        validate_certs: false
