---
- name: OpenShift Node Firewall Onboarding Workflow
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    node_name: "{{ target_node_name }}"

  tasks:
    - name: Remove taint from Machine resource
      kubernetes.core.k8s:
        validate_certs: "{{ validate_certs }}"
        definition:
          apiVersion: machine.openshift.io/v1beta1
          kind: Machine
          metadata:
            name: "{{ target_node_name }}"
            namespace: openshift-machine-api
            labels:
              trigger-app-onboarding: null
          spec:
            taints: []

    - name: Remove Taint and Label from OpenShift Node
      kubernetes.core.k8s:
        validate_certs: false
        definition:
          apiVersion: v1
          kind: Node
          metadata:
            name: "{{ node_name }}"
            labels:
              trigger-aap-onboarding: null # Setting null removes the label
          spec:
            taints: [] # Strips all onboarding taints from the Node



